**Часть 1.**

**__1.__ Установить, какие произведения матриц $AB$ и $BA$ определены, и найти размерности полученных матриц:**

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

**а)** $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$

Ответ: оба произведения ${\color {red}{AB}}$ и ${\color {red}{BA\ не\ определены}}$.

**б)** $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$

Ответ: определено произведение ${\color {red}{AB}}$, размерность новой матрицы будет ${\color {red}{2\times 3}}$. Произведение ${\color {red}{BA\ не\ определено}}$

**в)** $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$

Ответ: оба произведения $AB$ и $BA$ определены, размерность матрицы ${\color {red}{AB}}$ будет ${\color {red}{8\times 8}}$, размерность матрицы ${\color {red}{BA}}$ будет ${\color {red}{3\times 3}}$.

**г)** $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$

Ответ: оба произведения ${\color {red}{AB}}$ и ${\color {red}{BA}}$ определены, размерность обеих матриц будет ${\color {red}{4\times 4}}$.

**__2.__ Найти сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$**

Найдем сумму данных матриц:

A + B = $\begin{pmatrix}
1 & -2 \\ 
3 & 0 \\ 
\end{pmatrix} + \begin{pmatrix}
4 & -1 \\ 
0 & 5 \\ 
\end{pmatrix} = {\color {red}{\begin{pmatrix}
5 & -3 \\ 
3 & 5 \\ 
\end{pmatrix}}}$

Найдем произведения данных матриц:

AB = $\begin{pmatrix}
1 & -2 \\ 
3 & 0 \\ 
\end{pmatrix} * \begin{pmatrix}
4 & -1 \\ 
0 & 5 \\ 
\end{pmatrix} = \begin{pmatrix}
1*4+(-2)*0 & 1*(-1)+(-2)*5 \\ 
3*4+0*0 & 3*(-1)+0*5 \\ 
\end{pmatrix} = {\color {red}{\begin{pmatrix}
4 & -11 \\ 
12 & -3 \\ 
\end{pmatrix}}}$

BA = $\begin{pmatrix}
4 & -1 \\ 
0 & 5 \\ 
\end{pmatrix} * \begin{pmatrix}
1 & -2 \\ 
3 & 0 \\ 
\end{pmatrix} = \begin{pmatrix}
4*1-1*3 & 4*(-2)-1*0 \\ 
0*1+5*3 & 0*(-2)+5*0 \\ 
\end{pmatrix} = {\color {red}{\begin{pmatrix}
1 & -8 \\ 
15 & 0 \\ 
\end{pmatrix}}}$

In [2]:
import numpy as np

A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])

print(f'Матрица С = A + B\n{A + B}')
print(f'Матрица С = A * B\n{np.dot(A, B)}')
print(f'Матрица С = B * A\n{np.dot(B, A)}')

Матрица С = A + B
[[ 5 -3]
 [ 3  5]]
Матрица С = A * B
[[  4 -11]
 [ 12  -3]]
Матрица С = B * A
[[ 1 -8]
 [15  0]]


**__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислить линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$**

Посчитаем линейную комбинацию:

$3A-2B+4C = 3 * \begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix} - 2 * \begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix} + 4 * \begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix} = \begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix} + \begin{pmatrix}
0 & -10\\ 
-4 & 2
\end{pmatrix} + \begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix} = {\color {red}{\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}}}$

In [ ]:
import numpy as np

A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица 3A−2B+4C\n{3 * A - 2 * B + 4 * C}')

Матрица 3A−2B+4C
[[ 11  -5]
 [  9 -12]]


**__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислить $AA^{T}$ и $A^{T}A$.**

$A^T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix}$

$AA^T=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix} * \begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} = \begin{pmatrix}
4*4+1*1 & 4*5+1*(-2) & 4*2+1*3\\ 
5*4+(-2)*1 & 5*5+(-2)*(-2) & 5*2+(-2)*3\\ 
2*4+3*1 & 2*5+3*(-2) & 2*2+3*3\\ 
\end{pmatrix}= {\color {red}{\begin{pmatrix}
17 & 18 & 11\\ 
18 & 29 & 4\\ 
11 & 4 & 13\\ 
\end{pmatrix}}}$

$A^TA=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3\\ 
\end{pmatrix} * \begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}  = \begin{pmatrix}
4*4+5*5+2*2 & 4*1+5*(-2)+2*3\\ 
1*4+(-2)*5+3*2 & 1*1+(-2)*(-2)+3*3\\ 
\end{pmatrix}= {\color {red}{\begin{pmatrix}
45 & 0 \\ 
0 & 14 \\ 
\end{pmatrix}}}$

In [ ]:
import numpy as np

A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица A^T\n{A.T}')
print(f'Матрица AA^T\n{np.dot(A, A.T)}')
print(f'Матрица A^TA\n{np.dot(A.T, A)}')

Матрица A^T
[[ 4  5  2]
 [ 1 -2  3]]
Матрица AA^T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A^TA
[[45  0]
 [ 0 14]]


**__5*.__ Написать на Python функцию для перемножения двух произвольных матриц, не используя NumPy.**

In [ ]:
def matrixdot(matrix_1, matrix_2):
  
  #Заполняем будущую матрицу нулями
  result_matrix = [[0 for i in range(len(matrix_2[0]))] for i in range(len(matrix_1))]
  
  # Проверяем размерности входящих матриц
  if len(matrix_1[0]) == len(matrix_2):

    # Находим произведение входящих матриц
    for i in range(0, len(matrix_1)):
      for j in range(0, len(matrix_2[0])):
        result_matrix[i][j] = sum(matrix_1[i][k] * matrix_2[k][j] for k in range(len(matrix_2)))
    
    return result_matrix

  else:
    return "Размерности матриц не совпадают!"

In [ ]:
A = [[1, 7], [3, -6]]
B = [[0, 5, 7], [2, -1, 2]]

matrixdot(A, B)

[[14, -2, 21], [-12, 21, 9]]

In [3]:
# Решение

def skalar_prod(v1, v2):
    return sum([i * j for i, j in zip(v1, v2)])
       
def matrix_product(A, B, display_result=True):
    result = []
    try:
        for row_a in A:
            internal_row = []
            for k in range(len(B[0])):
                column = [B[i][k] for i in range(len(B))]
                internal_row.append(skalar_prod(row_a, column))
            result.append(internal_row)
        if display_result:
            for row in result:
                print(row)
        return result
    except Exception as e:
        print('wrong dimensions!')
        print(e)

In [4]:
# Проверка
a = [[1,2,3],
     [5,3,7]]
b = [[1,1],
     [2,2],
     [3,3]]
с = matrix_product(a,b)

[14, 14]
[32, 32]


In [5]:
# Сравнение с NUMPY
import numpy as np
a_np = np.array(a)
b_np = np.array(b)
a_np.dot(b_np)

array([[14, 14],
       [32, 32]])

**Часть 2.**

**__1.__ Вычислить определитель:**

   a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$

   б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$
    
   в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$

  **a)**

$\begin{vmatrix}
\sin x & -\cos x\\ 
\cos x & \sin x
\end{vmatrix} = \sin x * \sin x - \cos x * (- \cos x) = \sin ^2 x + \cos^2 x = {\color {red}{1}}$

   **б)**
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 4 * \begin{vmatrix}
5 & 1\\ 
0 & 9
\end{vmatrix} - 2 * \begin{vmatrix}
0 & 1\\ 
0 & 9
\end{vmatrix} + 3 * \begin{vmatrix}
0 & 5\\ 
0 & 0
\end{vmatrix} = 4 * (5 * 9 - 0 * 1) - 2 * (0 * 9 - 0 * 1) + 3 * (0 * 0 - 0 * 5) = 180 - 0 + 0 = {\color {red}{180}}$
    
   **в)**

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 1 * \begin{vmatrix}
5 & 6\\ 
8 & 9
\end{vmatrix} - 2 * \begin{vmatrix}
4 & 6\\ 
7 & 9
\end{vmatrix} + 3 * \begin{vmatrix}
4 & 5\\ 
7 & 8
\end{vmatrix} = 1 * (5 * 9 - 8 * 6) - 2 * (4 * 9 - 7 * 6) + 3 * (4 * 8 - 7 * 5) = -3 + 12 -9 = {\color {red}{0}}$

In [ ]:
import numpy as np
import scipy.linalg

A = np.array([[np.sin(x), -np.cos(x)], [np.cos(x), np.sin(x)]])
x = 0
B = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])
C = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Определитель матрицы A:\n{np.linalg.det(A):.0f}')
print(f'Определитель матрицы B:\n{np.linalg.det(B):.0f}')
print(f'Определитель матрицы C:\n{np.linalg.det(C):.0f}')

Определитель матрицы A:
1
Определитель матрицы B:
180
Определитель матрицы C:
0


**__2.__ Определитель матрицы $A$ равен $4$. Найти:**

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

   **а)** Воспользуемся свойством определителя. Для двух квадратных матриц одинакового размера $det(AB)=detA * detB$.

$det(A^{2}) = detA * detA = 4 * 4 = {\color {red}{16}}$
    
   **б)** Воспользуемся свойством определителя. Определитель транспонированной матрицы равен определителю исходной: $detA^{T}=detA$.
   
   $det(A^{T}) = {\color {red}{4}}$
    
   **в)** Воспользуемся свойством определителя. Если квадратная матрица $n$-го порядка умножается на некоторое ненулевое число $\lambda$, то определитель полученной матрицы равен произведению определителя исходной матрицы  на число  в степени, равной порядку матрицы $\lambda A = \lambda^n A$.

   Так как порядок матрицы не задан, получаем:
   
   $det(2A) = {\color {red}{2^n * 4}}$.

In [ ]:
import numpy as np
import scipy.linalg

A = np.array([[2, 0], [0, 2]])
A_ = np.array([[2, 0, 0], [0, 2, 0] , [0, 0, 1]])

print(f'Определитель матрицы A:\n{np.linalg.det(A):.0f}')
print(f'Определитель матрицы A^2:\n{np.linalg.det(A*A):.0f}')
print(f'Определитель матрицы A^T:\n{np.linalg.det(A.T):.0f}')
print(f'Определитель матрицы 2-го порядка 2A:\n{np.linalg.det(2*A):.0f}')
print(f'Определитель матрицы 3-го порядка 2A_:\n{np.linalg.det(2*A_):.0f}')

Определитель матрицы A:
4
Определитель матрицы A^2:
16
Определитель матрицы A^T:
4
Определитель матрицы 2-го порядка 2A:
16
Определитель матрицы 3-го порядка 2A_:
32


**__3.__  Доказать, что матрица**

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$
   
**вырожденная.**

Матрица является вырожденной, когда ее определитель равен нулю. Найдем определитель матрицы:

$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix} = \begin{pmatrix}
12 & -42 & 18\\ 
0 & -14 & 70\\ 
0 & 0 & 0
\end{pmatrix} = 12 * (-14) * 0 = {\color {red}{0}}$

Определитель матрицы равен нулю, следовательно она является вырожденной.

In [ ]:
import numpy as np
import scipy.linalg

A = np.array([[-2, 7, -3], [4, -14, 6], [-3, 7, 13]])

print(f'Определитель матрицы A:\n{np.linalg.det(A):.0f}')

Определитель матрицы A:
0


**__4.__ Найти ранг матрицы:**

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

   **а)** Ранг матрицы равен ${\color {red}{2}}$.
   
   $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} = \begin{pmatrix}
-2 & -4 & -6\\ 
0 & 1 & 2\\
\end{pmatrix}$

   **б)** Ранг матрицы равен ${\color {red}{3}}$.
   
   $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} = \begin{pmatrix}
2 & 3 & 5 & 6 \\
0 & 0 & 4 & 3\\ 
0 & 0 & 2 & 2
\end{pmatrix}$

In [ ]:
import numpy as np
import scipy.linalg

A = np.array([[1, 2, 3], [1, 1, 1], [2, 3, 4]])
B = np.array([[0, 0, 2, 1], [0, 0, 2, 2], [0, 0, 4, 3], [2, 3, 5, 6]])
rA = np.linalg.matrix_rank(A)
rB = np.linalg.matrix_rank(B)

print(f'Ранг матрицы A: {rA}')
print(f'Ранг матрицы B: {rB}')

Ранг матрицы A: 2
Ранг матрицы B: 3
