**__1.__ Найти собственные векторы и собственные значения для линейного оператора, заданного матрицей**

$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$

Найдем собственные значения линейного оператора, составив и решив характеристическое уравнение:

$\begin{vmatrix}
-1-\lambda & -6\\ 
2 & 6-\lambda
\end{vmatrix} = 0$

$(-1-\lambda)(6-\lambda)-2*(-6)=0$

$-6+\lambda-6\lambda+\lambda^2+12=0$

$\lambda^2-5\lambda+6=0$

$\lambda_1 = 2\ \ \ \ \lambda_2 = 3$

Найдем собственные векторы вида $\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$, подставив полученные собственные значения в выражение $\textbf{A}x=\lambda x$:

$\begin{pmatrix}
a & b\\ 
c & d
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}=
\lambda
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}.
$

**Для $\lambda_1 = 2$:**

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}= 2 *
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

Решим систему вида:

$\begin{cases}
ax_{1}+bx_{2}=\lambda x_{1} \\
cx_{1}+dx_{2}=\lambda x_{2}
\end{cases}$ 

Подставим значения:

$\begin{cases}
-1x_{1}-6x_{2} - 2x_{1} = 0 \\
2x_{1}+6x_{2} - 2x_{2} = 0
\end{cases}\,\,\,\,\,\Rightarrow\,\,\,\,\,
\begin{cases}
-3x_{1}-6x_{2} = 0 \\
2x_{1}+4x_{2} = 0
\end{cases}\,\,\,\,\,\Rightarrow\,\,\,\,\,
\begin{cases}
x_{1} = -2x_{2}\\
0 = 0
\end{cases}$ 

Получаем вектор ${\color {red}{\begin{pmatrix}
-2x_{2}\\ 
x_{2}
\end{pmatrix}}}$. При этом $x_{2}$ можно взять любым. Пусть $x_{2}$ будет равен $2$, тогда собственный вектор будет равен ${\color {red}{\begin{pmatrix}
-4\\ 
2
\end{pmatrix}}}$.

**Для $\lambda_1 = 3$:**

$\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}= 3 *
\begin{pmatrix}
x_{1}\\ 
x_{2}
\end{pmatrix}$

Подставим значения:

$\begin{cases}
-1x_{1}-6x_{2} - 3x_{1} = 0 \\
2x_{1}+6x_{2} - 3x_{2} = 0
\end{cases}\,\,\,\,\,\Rightarrow\,\,\,\,\,
\begin{cases}
-4x_{1}-6x_{2} = 0 \\
2x_{1}+3x_{2} = 0
\end{cases}\,\,\,\,\,\Rightarrow\,\,\,\,\,
\begin{cases}
x_{1} = -\frac{3}{2}x_{2}\\
0 = 0
\end{cases}$

Получаем вектор ${\color {red}{\begin{pmatrix}
-\frac{3}{2}x_{2}\\ 
x_{2}
\end{pmatrix}}}$. При этом $x_{2}$ можно взять любым. Пусть $x_{2}$ будет равен $2$, тогда собственный вектор будет равен ${\color {red}{\begin{pmatrix}
-3\\ 
2
\end{pmatrix}}}$.

In [23]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}\n')

print(f'v1\n{v.T[1]}')
print(f'v1\n{v[:, 1]}')
print(f'\n{v.T[1].dot(v.T[1])}')

Матрица A:
[[-1 -6]
 [ 2  6]]

Собственные значения:
[2. 3.]
Собственные векторы:
[[-0.89  0.83]
 [ 0.45 -0.55]]

v1
[ 0.83 -0.55]
v1
[ 0.83 -0.55]

1.0


**__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей**

$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$

**Показать, что __любой__ вектор является для него собственным.**

Составим характеристическое уравнение:

$\begin{vmatrix}
-1-\lambda & 0\\ 
0 & -1-\lambda
\end{vmatrix}=0$

$(-1-\lambda)^{2} - 0 = 0$

$\lambda = -1$

Подставим значения:

$\begin{cases}
-x_{1} + 0 + x_{1} = 0 \\
0 - x_{2} + x_{2} = 0
\end{cases}\,\,\,\,\,\Rightarrow\,\,\,\,\,
{\color {red}{\begin{cases}
0 = 0\\
0 = 0
\end{cases}}}$

Так как в левой части обоих уравнений получаются нули, то вместо $x_{1}$ и $x_{2}$ можно взять любые значения. Следовательно, любой вектор будет являться собственным для заданной матрицы.

In [31]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[-1, 0], [0, -1]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}\n')

Матрица A:
[[-1  0]
 [ 0 -1]]

Собственные значения:
[-1. -1.]
Собственные векторы:
[[1. 0.]
 [0. 1.]]



**__3.__ Пусть линейный оператор задан матрицей**

$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$

**Установить, является ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.**

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором:

$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\ 
1 
\end{pmatrix}=
\lambda
\begin{pmatrix}
1\\ 
1
\end{pmatrix}$

Из этого будет следовать, что:

$\begin{cases}
1+1=1*\lambda \\ 
-1+3 = 1*\lambda
\end{cases}
\Rightarrow
{\color {red}{\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}}}$

Так как $\lambda$ в обоих случая равна $2$, следовательно, вектор $x=(1,1)$  **является** собственным вектором линейного оператора, заданного матрицей $A$.

In [32]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[1, 1], [-1, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}\n')

Матрица A:
[[ 1  1]
 [-1  3]]

Собственные значения:
[2. 2.]
Собственные векторы:
[[ 0.71 -0.71]
 [ 0.71 -0.71]]



**__4.__ Пусть линейный оператор задан матрицей**

$A=\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}.$

**Установить, является ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.**

Предположим, что вектор $x$ является собственным вектором заданного линейного оператора, тогда должно существовать некоторое вещественное число $\lambda$, при котором:

$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\ 
-3\\
-4 
\end{pmatrix}=
\lambda
\begin{pmatrix}
3\\ 
-3\\
-4
\end{pmatrix}$

Из этого будет следовать, что:

$\begin{cases}
0-9+0=3*\lambda \\ 
9+0+0 = -3*\lambda \\
0+0-12=-4*\lambda \\ 
\end{cases}
\Rightarrow
{\color {red}{\begin{cases}
\lambda=-3\\ 
\lambda=-3\\
\lambda=3\\
\end{cases}}}$

Так как $\lambda$ не равна одному и тому же числу, следовательно, вектор $x=(3,-3, -4)$  **не является** собственным вектором линейного оператора, заданного матрицей $A$.

In [33]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
w, v = np.linalg.eig(A)

print(f'Матрица A:\n{A}\n')
print(f'Собственные значения:\n{w}')
print(f'Собственные векторы:\n{v}\n')

Матрица A:
[[0 3 0]
 [3 0 0]
 [0 0 3]]

Собственные значения:
[ 3. -3.  3.]
Собственные векторы:
[[ 0.71 -0.71  0.  ]
 [ 0.71  0.71  0.  ]
 [ 0.    0.    1.  ]]

