**1. Найти с помощью NumPy SVD для матрицы**

$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$

In [32]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

U, s, W = np.linalg.svd(A)

# Приводим список диагональных элементов к виду диагональной матрицы
D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица A:\n{A}\n')
print(f'Матрица U:\n{U}\n')
print(f'Матрица D:\n{D}\n')
print(f'Матрица W:\n{W}\n')
print(f'Проверка:\n{np.dot(np.dot(U, D), W)}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]

Матрица U:
[[ 0.17  0.16 -0.53 -0.8  -0.16]
 [ 0.39 -0.53  0.61 -0.43  0.03]
 [-0.14 -0.82 -0.52  0.14  0.07]
 [ 0.89  0.06 -0.25  0.38 -0.06]
 [ 0.08  0.11 -0.08 -0.11  0.98]]

Матрица D:
[[8.82 0.   0.  ]
 [0.   6.14 0.  ]
 [0.   0.   2.53]
 [0.   0.   0.  ]
 [0.   0.   0.  ]]

Матрица W:
[[ 0.07  0.72  0.69]
 [-0.37  0.67 -0.65]
 [-0.93 -0.21  0.31]]

Проверка:
[[ 1.  2.  0.]
 [ 0. -0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [-0.  1. -0.]]


**2. Для матрицы из предыдущего задания найти:**

**а) евклидову норму;**
    
**б) норму Фробениуса.**

In [34]:
import numpy as np

np.set_printoptions(precision=2, suppress=True)

A = np.array([[1, 2, 0],
              [0, 0, 5],
              [3, -4, 2],
              [1, 6, 5],
              [0, 1, 0]])

U, s, W = np.linalg.svd(A)

# Евклидова норма матрицы A
Enorm = np.linalg.norm(A, ord=2)

# Норма Фробениуса матрицы A
Fnorm = np.linalg.norm(A, ord="fro")

# Норма Фробениуса через перемножение значений диагональной матрицы D
dlist = []
for i in range(0, s.shape[0]):
  dlist.append(s[i]**2)
Fdnorm = np.sqrt(sum(dlist))

# Норма Фробениуса через перемножение всех значений матрицы A
dlist = []
for i in range(0, A.shape[0]):
  for j in range(0, A.shape[1]):
    dlist.append(A[i][j]**2)
Fanorm = np.sqrt(sum(dlist))

print(f'а) Евклидова норма матрицы A: {Enorm:.2f}')
print(f'Проверка по максимальному значению M1 диагональной матрицы D: {round(s[0], 14) == round(Enorm, 14)}\n')
print(f'б) Норма Фробениуса матрицы A: {Fnorm:.2f}')
print(f'Проверка через перемножение значений диагональной матрицы D: {Fdnorm == Fnorm}')
print(f'Проверка через перемножение всех значений матрицы A: {Fanorm == Fnorm}')

а) Евклидова норма матрицы A: 8.82
Проверка по максимальному значению M1 диагональной матрицы D: True

б) Норма Фробениуса матрицы A: 11.05
Проверка через перемножение значений диагональной матрицы D: True
Проверка через перемножение всех значений матрицы A: True
